// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunService":       schema_pkg_apis_thoth_v1alpha1_AmunService(ref),
		"github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceSpec":   schema_pkg_apis_thoth_v1alpha1_AmunServiceSpec(ref),
		"github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceStatus": schema_pkg_apis_thoth_v1alpha1_AmunServiceStatus(ref),
	}
}

func schema_pkg_apis_thoth_v1alpha1_AmunService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AmunService is the Schema for the amunservices API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceSpec", "github.com/sub-mod/amun-operator/pkg/apis/thoth/v1alpha1.AmunServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_thoth_v1alpha1_AmunServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AmunServiceSpec defines the desired state of AmunService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_thoth_v1alpha1_AmunServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AmunServiceStatus defines the observed state of AmunService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
