apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: amunservices.thoth.redhat.com
spec:
  group: thoth.redhat.com
  names:
    kind: AmunService
    listKind: AmunServiceList
    plural: amunservices
    singular: amunservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  description: Base Image for BuildConfig.
                  type: string
                script:
                  type: string
                packages:
                  description: List of
                  items:
                    type: string
                  type: array
                hardwareLabels:
                  description: The labels to identify nodes with hardware
                  type: object
                runResources:
                  description: BuildResources define the resources for Docker Build.
                  properties:
                    cpuLimit:
                      description: The maximum cpu requested.
                      type: string
                    memoryLimit:
                      description: The maximum memory requested.
                      type: string
                    CpuRequests:
                      description: The cpu requested.
                      type: string
                    MemoryRequests:
                      description: The memory requested.
                      type: string
                  required:
                    - cpuLimit
                    - memoryLimit
                    - CpuRequests
                    - MemoryRequests
                  type: object
                buildResources:
                  description: BuildResources define the resources for Docker Build.
                  properties:
                    cpuLimit:
                      description: The maximum cpu requested.
                      type: string
                    memoryLimit:
                      description: The maximum memory requested.
                      type: string
                    CpuRequests:
                      description: The cpu requested.
                      type: string
                    MemoryRequests:
                      description: The memory requested.
                      type: string
                  required:
                    - cpuLimit
                    - memoryLimit
                    - CpuRequests
                    - MemoryRequests
                  type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
