apiVersion: apps/v1
kind: Deployment
metadata:
  name: amun-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amun-operator
  template:
    metadata:
      labels:
        name: amun-operator
    spec:
      serviceAccountName: amun-operator
      containers:
        - name: amun-operator
          # Replace this with the built image name
          image: quay.io/sub_mod/amun-operator:latest
          command:
          - amun-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "amun-operator"
